export const cardPacks = {
  Order_Shift: { name: 'Order Shift', value: 10030 },
  Heroes_of_Rivenbrandt: { name: 'Heroes of Rivenbrandt', value: 10029 },
  Academy_of_Ages: { name: 'Academy of Ages', value: 10028 },
  Eightfold_Abyss_Azvaldt: { name: 'Eightfold Abyss Azvaldt', value: 10027 },
  Celestial_Dragonblade: { name: 'Celestial Dragonblade', value: 10026 },
  Roar_of_the_Godwyrm: { name: 'Roar of the Godwyrm', value: 10025 },
  Edge_of_Paradise: { name: 'Edge of Paradise', value: 10024 },
  Omen_of_Storms: { name: 'Omen of Storms', value: 10023 },
  Dawn_of_Calamity: { name: 'Dawn of Calamity', value: 10022 },
  Renascent_Chronicles: { name: 'Renascent Chronicles', value: 10021 },
  Darkness_Over_Vellsar: { name: 'Darkness Over Vellsar', value: 10020 },
  Eternal_Awakening: { name: 'Eternal Awakening', value: 10019 },
  Storm_Over_Rivayle: { name: 'Storm Over Rivayle', value: 10018 },
  Fortunes_Hand: { name: 'Fortunes Hand', value: 10017 },
  World_Uprooted: { name: 'World Uprooted', value: 10016 },
  Ultimate_Colosseum: { name: 'Ultimate Colosseum', value: 10015 },
  Verdant_Conflict: { name: 'Verdant Conflict', value: 10014 },
  Rebirth_of_Glory: { name: 'Rebirth of Glory', value: 10013 },
  Steel_Rebellion: { name: 'Steel Rebellion', value: 10012 },
  Altersphere: { name: 'Altersphere', value: 10011 },
  Omen_of_the_Ten: { name: 'Omen of the Ten', value: 10010 },
  Brigade_of_the_Sky: { name: 'Brigade of the Sky', value: 10019 },
  Dawnbreak_Nightedge: { name: 'Dawnbreak, Nightedge', value: 10008 },
  Chronogenesis: { name: 'Chronogenesis', value: 10006 },
  Starforged_Legends: { name: 'Starforged Legends', value: 10005 },
  Wonderland_Dreams: { name: 'Wonderland Dreams', value: 10004 },
  Tempest_of_the_Gods: { name: 'Tempest of the Gods', value: 10003 },
  Rise_of_Bahamut: { name: 'Rise of Bahamut', value: 10002 },
  Darkness_Evolved: { name: 'Darkness Evolved', value: 10001 },
  Classic: { name: 'Classic', value: 10000 },
  Basic: { name: 'Basic', value: 9999 },
  Token: { name: 'Token', value: 9998 },
} as const;

export const crafts = {
  Forestcraft: { name: 'Forestcraft', iconCardId: 1111410100, value: 1 },
  Swordcraft: { name: 'Swordcraft', iconCardId: 1052210300, value: 2 },
  Runecraft: { name: 'Runecraft', iconCardId: 900311020, value: 3 },
  Dragoncraft: { name: 'Dragoncraft', iconCardId: 1124110300, value: 4 },
  Shadowcraft: { name: 'Shadowcraft', iconCardId: 900541090, value: 5 },
  Bloodcraft: { name: 'Bloodcraft', iconCardId: 1106110200, value: 6 },
  Havencraft: { name: 'Havencraft', iconCardId: 1117410300, value: 7 },
  Portalcraft: { name: 'Portalcraft', iconCardId: 900841090, value: 8 },
  Neutral: { name: 'Neutral', iconCardId: 1080110200, value: 0 },
} as const;

export const rarities = {
  Bronze: { name: 'Bronze', value: 1 },
  Silver: { name: 'Silver', value: 2 },
  Gold: { name: 'Gold', value: 3 },
  Legendary: { name: 'Legendary', value: 4 },
} as const;

export const formats = {
  Rotation: { name: 'Rotation', value: 1 },
  Unlimited: { name: 'Unlimited', value: 3 },
} as const;

export const types = {
  Followers: { name: 'Follower', value: 1 },
  Spell: { name: 'Spell', value: 2 },
  Amulets: { name: 'Amulet', value: 3 },
} as const;

export const costs = {
  0: { name: '0', value: 0 },
  1: { name: '1', value: 1 },
  2: { name: '2', value: 2 },
  3: { name: '3', value: 3 },
  4: { name: '4', value: 4 },
  5: { name: '5', value: 5 },
  6: { name: '6', value: 6 },
  7: { name: '7', value: 7 },
  8: { name: '8', value: 8 },
  9: { name: '9', value: 9 },
  10: { name: '10+', value: 10 },
} as const;

export const abilities = {
  fanfare: { name: 'Fanfare', value: 1 },
  Last_Words: { name: 'Last Words', value: 2 },
  Evolve: { name: 'Evolve', value: 3 },
  Strike: { name: 'Strike', value: 4 },
  Ward: { name: 'Ward', value: 5 },
  Storm: { name: 'Storm', value: 6 },
  Ambush: { name: 'Ambush', value: 7 },
  Bane: { name: 'Bane', value: 8 },
  Drain: { name: 'Drain', value: 9 },
  Overflow: { name: 'Overflow', value: 10 },
  Vengeance: { name: 'Vengeance', value: 11 },
  Spellboost: { name: 'Spellboost', value: 12 },
  Countdown: { name: 'Countdown', value: 13 },
  Necromancy: { name: 'Necromancy', value: 14 },
  Earth_Rite: { name: 'Earth Rite', value: 15 },
  Rush: { name: 'Rush', value: 16 },
  Clash: { name: 'Clash', value: 17 },
  Enhance: { name: 'Enhance', value: 18 },
  Reanimate: { name: 'Reanimate', value: 19 },
  Burial_Rite: { name: 'Burial Rite', value: 20 },
  Resonance: { name: 'Resonance', value: 21 },
  Choose: { name: 'Choose', value: 22 },
  Accelerate: { name: 'Accelerate', value: 23 },
  Invocation: { name: 'Invocation', value: 24 },
  Crystallize: { name: 'Crystallize', value: 25 },
  Union_Burst: { name: 'Union Burst', value: 26 },
  Avarice: { name: 'Avarice', value: 27 },
  Wrath: { name: 'Wrath', value: 28 },
  Rusion: { name: 'Fusion', value: 29 },
  Rally: { name: 'Rally', value: 30 },
  Maneuver: { name: 'Maneuver', value: 31 },
  Skybound_art: { name: 'Skybound Art', value: 32 },
  Stack: { name: 'Stack', value: 33 },
} as const;

export const attacks = {
  0: { name: '0', value: 0 },
  1: { name: '1', value: 1 },
  2: { name: '2', value: 2 },
  3: { name: '3', value: 3 },
  4: { name: '4', value: 4 },
  5: { name: '5', value: 5 },
  6: { name: '6', value: 6 },
  7: { name: '7', value: 7 },
  8: { name: '8', value: 8 },
  9: { name: '9', value: 9 },
  10: { name: '10+', value: 10 },
} as const;

export const defences = {
  0: { name: '0', value: 0 },
  1: { name: '1', value: 1 },
  2: { name: '2', value: 2 },
  3: { name: '3', value: 3 },
  4: { name: '4', value: 4 },
  5: { name: '5', value: 5 },
  6: { name: '6', value: 6 },
  7: { name: '7', value: 7 },
  8: { name: '8', value: 8 },
  9: { name: '9', value: 9 },
  10: { name: '10+', value: 10 },
} as const;

export const traits = {
  Officer: { name: 'Officer', value: 1 },
  Commander: { name: 'Commander', value: 2 },
  Earth_Sigil: { name: 'Earth Sigil', value: 3 },
  Mysteria: { name: 'Mysteria', value: 4 },
  Artifact: { name: 'Artifact', value: 5 },
  Loot: { name: 'Loot', value: 6 },
  Machina: { name: 'Machina', value: 7 },
  Levin: { name: 'Levin', value: 8 },
  Natura: { name: 'Natura', value: 9 },
  Festive: { name: 'Festive', value: 10 },
  Heroic: { name: 'Heroic', value: 11 },
  Chess: { name: 'Chess', value: 12 },
  Armed: { name: 'Armed', value: 13 },
  Condemned: { name: 'Condemned', value: 14 },
  All: { name: 'All', value: 15 },
  Academic: { name: 'Academic', value: 16 },
} as const;
